name: Lint Workflow

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: API

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'  # You can use a Node.js version compatible with your Python linting tools

    - name: Install dependencies
      run: |
        yarn install
        pip install flake8  # Install Flake8 for Python linting

    - name: Lint with yarn
      run: yarn lint

    - name: Lint Python files
      run: flake8 .  # Replace "." with the directory or files you want to lint
