name: serverless-deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Choose an appropriate Node.js version
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Install Serverless Framework
        run: npm install -g serverless
      - name: Create env
        run: python3 -m venv test_venv
      - name: Activate env
        run: source test_venv/bin/activate
      - name: Install boto3
        run: pip install boto3 -t boto3
      - name: Install fpdf
        run: pip install fpdf -t fpdf
      - name: Upload to AWS
        run: sls deploy --stage demo
