name: serverless-deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        # This is the version of the action for setting up Python, not the Python version.
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.10.x'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Create env
        run: python3 -m venv test_venv
      - name: Activate env
        run: source test_venv/bin/activate
      - name: Make boto3 directory
        run: mkdir boto3 
      - name: Install boto3
        run: pip install boto3 -t boto3
      - name: Make fpdf directory
        run: mkdir fpdf 
      - name: Install fpdf
        run: pip install fpdf -t fpdf
      - name: Upload to AWS
        run: sls deploy --stage demo
